language: node_js
node_js:
  - "7.8.0"
cache:
  yarn: true
  directories:
    - node_modules
#before_install:
#  - openssl aes-256-cbc -K $encrypted_638fac788039_key -iv $encrypted_638fac788039_iv -in .env.enc -out .env -d
#before_script:
#  - sleep 5
script:
  - npm run test
  - npm run lint-server
  - npm run lint-client
  - npm run build
#services:
#  - mongodb
