language: node_js
node_js:
  - "7.8.0"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - sudo cp .env.example .env
  - npm run test
  - npm run build:server
  - npm run build:client
#services:
#  - mongodb
